In [ ]:
!pip install GDAL

Requirement already satisfied: GDAL in /usr/local/lib/python3.11/dist-packages (3.8.4)

In [ ]:
# Install QGIS in Colab
!apt-get update
!apt-get install qgis python3-qgis

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,628 B]
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [4,909 kB]
Get:12 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1,801 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,399 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,561 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,067 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,257 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,750 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,040 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [4,587 kB]
Fetched 32.8 MB in 4s (7,288 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  avahi-daemon fonts-dejavu-core fonts-lyx gcr geoclue-2.0 glib-networking
  glib-networking-common glib-networking-services gnome-keyring
  gnome-keyring-pkcs11 grass-core grass-doc gsettings-desktop-schemas
  iio-sensor-proxy javascript-common libassimp5 libavahi-core7 libavahi-glib1
  libdaemon0 libdraco4 libevdev2 libexiv2-27 libfcgi-bin libfcgi0ldbl
  libfftw3-double3 libgck-1-0 libgcr-base-3-1 libgcr-ui-3-1 libglu1-mesa
  libgsl27 libgslcblas0 libgudev-1.0-0 libhyphen0 libimagequant0 libinput-bin
  libinput10 libjs-leaflet libjson-glib-1.0-0 libjson-glib-1.0-common
  liblbfgsb0 libmbim-glib4 libmbim-proxy libmd4c0 libmm-glib0 libmng2
  libmtdev1 libnl-genl-3-200 libnotify4 libnss-mdns libpam-gnome-keyring
  libpdal-plugin-e57 libpdal-plugin-faux libpdal-plugin-hdf
  libpdal-plugin-icebridge libpdal-plugin-pgpointcloud libpdal-plugins
  libpdal16 libprotobuf-lite23 libproxy1v5 libqca-qt5-2 libqca-qt5-2-plugins
  libqgis-3d3.34.15 libqgis-analysis3.34.15 libqgis-app3.34.15
  libqgis-core3.34.15 libqgis-customwidgets libqgis-gui3.34.15
  libqgis-native3.34.15 libqgis-server3.34.15 libqgisgrass8-3.34.15
  libqgispython3.34.15 libqmi-glib5 libqmi-proxy libqscintilla2-qt5-15
  libqscintilla2-qt5-l10n libqt53danimation5 libqt53dcore5 libqt53dextras5
  libqt53dinput5 libqt53dlogic5 libqt53dquickscene2d5 libqt53drender5
  libqt5charts5 libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5
  libqt5designercomponents5 libqt5gui5 libqt5help5 libqt5keychain1
  libqt5location5 libqt5multimedia5 libqt5multimediawidgets5 libqt5network5
  libqt5opengl5 libqt5pdf5 libqt5positioning5 libqt5positioningquick5
  libqt5printsupport5 libqt5qml5 libqt5qmlmodels5 libqt5quick5
  libqt5quickwidgets5 libqt5sensors5 libqt5serialport5 libqt5sql5
  libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5webchannel5 libqt5webkit5
  libqt5widgets5 libqt5xml5 libqwt-qt5-6 libraqm0 libsecret-1-0
  libsecret-common libsoup2.4-1 libsoup2.4-common libspatialindex6
  libsqlite3-mod-spatialite libudev1 libwacom-bin libwacom-common libwacom9
  libwoff1 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0
  libxcb-util1 libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1 libxkbcommon-x11-0
  libxsimd-dev libzip4 modemmanager p11-kit p11-kit-modules pinentry-gnome3
  proj-bin python-babel-localedata python-matplotlib-data python3-appdirs
  python3-attr python3-babel python3-beniget python3-brotli python3-bs4
  python3-certifi python3-chardet python3-cycler python3-dateutil
  python3-decorator python3-fonttools python3-fs python3-gast python3-html5lib
  python3-idna python3-ipython-genutils python3-jinja2 python3-jsonschema
  python3-jupyter-core python3-kiwisolver python3-lxml python3-lz4
  python3-matplotlib python3-mpmath python3-nbformat python3-olefile
  python3-owslib python3-packaging python3-pbr python3-pil python3-pil.imagetk
  python3-pkg-resources python3-plotly python3-ply python3-psycopg2
  python3-pygments python3-pyproj python3-pyqt5 python3-pyqt5.qsci
  python3-pyqt5.qtmultimedia python3-pyqt5.qtpositioning python3-pyqt5.qtsql
  python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-pyqt5.sip
  python3-pyrsistent python3-pythran python3-qgis-common python3-requests
  python3-scipy python3-setuptools python3-soupsieve python3-sympy
  python3-tenacity python3-traitlets python3-tz python3-ufolib2
  python3-unicodedata2 python3-urllib3 python3-webencodings python3-yaml
  qdoc-qt5 qgis-common qgis-plugin-grass qgis-plugin-grass-common
  qgis-provider-grass qgis-providers qgis-providers-common qhelpgenerator-qt5
  qml-module-qtcharts qt3d-assimpsceneimport-plugin
  qt3d-defaultgeometryloader-plugin qt3d-gltfsceneio-plugin
  qt3d-scene2d-plugin qt5-assistant qt5-gtk-platformtheme
  qt5-image-formats-plugin-pdf qt5-image-formats-plugins
  qtattributionsscanner-qt5 qtchooser qttools5-dev-tools qttranslations5-l10n
  session-migration systemd-hwe-hwdb udev unicode-data usb-modeswitch
  usb-modeswitch-data wpasupplicant
Suggested packages:
  avahi-autoipd grass-dev grass-gui e00compr avce00 gnuplot gpsbabel gpstrans
  netpbm python3-rpy2 python3-termcolor subversion grass grass-dev-doc apache2
  | lighttpd | httpd exiv2 libfftw3-bin libfftw3-dev gsl-ref-psdoc
  | gsl-doc-pdf | gsl-doc-info | gsl-ref-html gnome-shell
  | notification-daemon avahi-autoipd | zeroconf libqscintilla2-doc qtwayland5
  qt5-qmltooling-plugins libxsimd-doc pinentry-doc python-attr-doc
  python-cycler-doc python3-genshi python-jinja2-doc python-jsonschema-doc
  python3-pip python-lxml-doc dvipng fonts-staypuft ghostscript gir1.2-gtk-3.0
  inkscape ipython3 librsvg2-common python-matplotlib-doc python3-cairocffi
  python3-gi-cairo python3-gobject python3-sip python3-tornado
  texlive-extra-utils texlive-latex-extra python-mpmath-doc python3-gmpy2
  python-pil-doc python3-pandas python3-ipykernel python-ply-doc
  python-psycopg2-doc python-pygments-doc ttf-bitstream-vera python3-openssl
  python3-socks python-requests-doc python-scipy-doc python-setuptools-doc
  texlive-fonts-extra python-sympy-doc python-tenacity-doc qt5-doc comgt
  wvdial wpagui libengine-pkcs11-openssl
The following NEW packages will be installed:
  avahi-daemon fonts-dejavu-core fonts-lyx gcr geoclue-2.0 glib-networking
  glib-networking-common glib-networking-services gnome-keyring
  gnome-keyring-pkcs11 grass-core grass-doc gsettings-desktop-schemas
  iio-sensor-proxy javascript-common libassimp5 libavahi-core7 libavahi-glib1
  libdaemon0 libdraco4 libevdev2 libexiv2-27 libfcgi-bin libfcgi0ldbl
  libfftw3-double3 libgck-1-0 libgcr-base-3-1 libgcr-ui-3-1 libglu1-mesa
  libgsl27 libgslcblas0 libgudev-1.0-0 libhyphen0 libimagequant0 libinput-bin
  libinput10 libjs-leaflet libjson-glib-1.0-0 libjson-glib-1.0-common
  liblbfgsb0 libmbim-glib4 libmbim-proxy libmd4c0 libmm-glib0 libmng2
  libmtdev1 libnl-genl-3-200 libnotify4 libnss-mdns libpam-gnome-keyring
  libpdal-plugin-e57 libpdal-plugin-faux libpdal-plugin-hdf
  libpdal-plugin-icebridge libpdal-plugin-pgpointcloud libpdal-plugins
  libpdal16 libprotobuf-lite23 libproxy1v5 libqca-qt5-2 libqca-qt5-2-plugins
  libqgis-3d3.34.15 libqgis-analysis3.34.15 libqgis-app3.34.15
  libqgis-core3.34.15 libqgis-customwidgets libqgis-gui3.34.15
  libqgis-native3.34.15 libqgis-server3.34.15 libqgisgrass8-3.34.15
  libqgispython3.34.15 libqmi-glib5 libqmi-proxy libqscintilla2-qt5-15
  libqscintilla2-qt5-l10n libqt53danimation5 libqt53dcore5 libqt53dextras5
  libqt53dinput5 libqt53dlogic5 libqt53dquickscene2d5 libqt53drender5
  libqt5charts5 libqt5concurrent5 libqt5core5a libqt5dbus5 libqt5designer5
  libqt5designercomponents5 libqt5gui5 libqt5help5 libqt5keychain1
  libqt5location5 libqt5multimedia5 libqt5multimediawidgets5 libqt5network5
  libqt5opengl5 libqt5pdf5 libqt5positioning5 libqt5positioningquick5
  libqt5printsupport5 libqt5qml5 libqt5qmlmodels5 libqt5quick5
  libqt5quickwidgets5 libqt5sensors5 libqt5serialport5 libqt5sql5
  libqt5sql5-sqlite libqt5svg5 libqt5test5 libqt5webchannel5 libqt5webkit5
  libqt5widgets5 libqt5xml5 libqwt-qt5-6 libraqm0 libsecret-1-0
  libsecret-common libsoup2.4-1 libsoup2.4-common libspatialindex6
  libsqlite3-mod-spatialite libwacom-bin libwacom-common libwacom9 libwoff1
  libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-util1
  libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1 libxkbcommon-x11-0 libxsimd-dev
  libzip4 modemmanager p11-kit p11-kit-modules pinentry-gnome3 proj-bin
  python-babel-localedata python-matplotlib-data python3-appdirs python3-attr
  python3-babel python3-beniget python3-brotli python3-bs4 python3-certifi
  python3-chardet python3-cycler python3-dateutil python3-decorator
  python3-fonttools python3-fs python3-gast python3-html5lib python3-idna
  python3-ipython-genutils python3-jinja2 python3-jsonschema
  python3-jupyter-core python3-kiwisolver python3-lxml python3-lz4
  python3-matplotlib python3-mpmath python3-nbformat python3-olefile
  python3-owslib python3-packaging python3-pbr python3-pil python3-pil.imagetk
  python3-plotly python3-ply python3-psycopg2 python3-pygments python3-pyproj
  python3-pyqt5 python3-pyqt5.qsci python3-pyqt5.qtmultimedia
  python3-pyqt5.qtpositioning python3-pyqt5.qtsql python3-pyqt5.qtsvg
  python3-pyqt5.qtwebkit python3-pyqt5.sip python3-pyrsistent python3-pythran
  python3-qgis python3-qgis-common python3-requests python3-scipy
  python3-setuptools python3-soupsieve python3-sympy python3-tenacity
  python3-traitlets python3-tz python3-ufolib2 python3-unicodedata2
  python3-urllib3 python3-webencodings python3-yaml qdoc-qt5 qgis qgis-common
  qgis-plugin-grass qgis-plugin-grass-common qgis-provider-grass
  qgis-providers qgis-providers-common qhelpgenerator-qt5 qml-module-qtcharts
  qt3d-assimpsceneimport-plugin qt3d-defaultgeometryloader-plugin
  qt3d-gltfsceneio-plugin qt3d-scene2d-plugin qt5-assistant
  qt5-gtk-platformtheme qt5-image-formats-plugin-pdf qt5-image-formats-plugins
  qtattributionsscanner-qt5 qtchooser qttools5-dev-tools qttranslations5-l10n
  session-migration systemd-hwe-hwdb udev unicode-data usb-modeswitch
  usb-modeswitch-data wpasupplicant
The following packages will be upgraded:
  libudev1 python3-pkg-resources
2 upgraded, 235 newly installed, 0 to remove and 35 not upgraded.
Need to get 300 MB of archives.
After this operation, 1,042 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libavahi-core7 amd64 0.8-5ubuntu5.2 [90.8 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdaemon0 amd64 0.14-7.1ubuntu3 [14.1 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 avahi-daemon amd64 0.8-5ubuntu5.2 [69.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5core5a amd64 5.15.3+dfsg-2ubuntu0.2 [2,006 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libevdev2 amd64 1.12.1+dfsg-1 [39.5 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmtdev1 amd64 1.1.6-1build4 [14.5 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libudev1 amd64 249.11-0ubuntu3.16 [76.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgudev-1.0-0 amd64 1:237-2build1 [16.3 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwacom-common all 2.2.0-1 [54.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwacom9 amd64 2.2.0-1 [22.0 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libinput-bin amd64 1.20.0-1ubuntu0.3 [19.9 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libinput10 amd64 1.20.0-1ubuntu0.3 [131 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libmd4c0 amd64 0.4.8-1 [42.0 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5dbus5 amd64 5.15.3+dfsg-2ubuntu0.2 [222 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5network5 amd64 5.15.3+dfsg-2ubuntu0.2 [731 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-icccm4 amd64 0.4.1-1.1build2 [11.5 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-util1 amd64 0.4.0-1build2 [11.4 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-image0 amd64 0.4.0-2 [11.5 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-keysyms1 amd64 0.4.0-1build3 [8,746 B]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-render-util0 amd64 0.3.9-1build3 [10.3 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xinerama0 amd64 1.14-3ubuntu3 [5,414 B]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xinput0 amd64 1.14-3ubuntu3 [34.3 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xkb1 amd64 1.14-3ubuntu3 [32.8 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbcommon-x11-0 amd64 1.4.0-1 [14.4 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5gui5 amd64 5.15.3+dfsg-2ubuntu0.2 [3,722 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5widgets5 amd64 5.15.3+dfsg-2ubuntu0.2 [2,561 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5svg5 amd64 5.15.3-1 [149 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhyphen0 amd64 2.8.8-7build2 [28.2 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5positioning5 amd64 5.15.3+dfsg-3 [223 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5printsupport5 amd64 5.15.3+dfsg-2ubuntu0.2 [214 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5qml5 amd64 5.15.3+dfsg-1 [1,472 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5qmlmodels5 amd64 5.15.3+dfsg-1 [205 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5quick5 amd64 5.15.3+dfsg-1 [1,748 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5sensors5 amd64 5.15.3-1 [123 kB]
Get:35 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5webchannel5 amd64 5.15.3-1 [62.9 kB]
Get:36 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwoff1 amd64 1.0.2-1build4 [45.2 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5webkit5 amd64 5.212.0~alpha4-15ubuntu1 [12.8 MB]
Get:38 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 qgis-providers-common all 3.34.15+dfsg-1~jammy2 [4,835 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqca-qt5-2 amd64 2.3.4-1build1 [340 kB]
Get:40 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqca-qt5-2-plugins amd64 2.3.4-1build1 [211 kB]
Get:41 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5sql5 amd64 5.15.3+dfsg-2ubuntu0.2 [123 kB]
Get:42 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5sql5-sqlite amd64 5.15.3+dfsg-2ubuntu0.2 [53.0 kB]
Get:43 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libmng2 amd64 2.0.3+dfsg-3 [168 kB]
Get:44 http://archive.ubuntu.com/ubuntu jammy/universe amd64 qt5-image-formats-plugins amd64 5.15.3-1 [49.6 kB]
Get:45 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libgslcblas0 amd64 2.7.1+dfsg-3 [94.4 kB]
Get:46 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libgsl27 amd64 2.7.1+dfsg-3 [1,000 kB]
Get:47 http://archive.ubuntu.com/ubuntu jammy/main amd64 libexiv2-27 amd64 0.27.5-3ubuntu1 [844 kB]
Get:48 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libprotobuf-lite23 amd64 3.12.4-1ubuntu7.22.04.2 [209 kB]
Get:49 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5concurrent5 amd64 5.15.3+dfsg-2ubuntu0.2 [36.3 kB]
Get:50 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5keychain1 amd64 0.13.2-5 [51.1 kB]
Get:51 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5serialport5 amd64 5.15.3-1 [34.6 kB]
Get:52 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5xml5 amd64 5.15.3+dfsg-2ubuntu0.2 [124 kB]
Get:53 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libspatialindex6 amd64 1.9.3-2 [247 kB]
Get:54 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libzip4 amd64 1.7.3-1ubuntu2 [55.0 kB]
Get:55 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqscintilla2-qt5-l10n all 2.11.6+dfsg-4 [54.8 kB]
Get:56 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqscintilla2-qt5-15 amd64 2.11.6+dfsg-4 [1,217 kB]
Get:57 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5multimedia5 amd64 5.15.3-1 [320 kB]
Get:58 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5multimediawidgets5 amd64 5.15.3-1 [42.6 kB]
Get:59 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5quickwidgets5 amd64 5.15.3+dfsg-1 [39.9 kB]
Get:60 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5opengl5 amd64 5.15.3+dfsg-2ubuntu0.2 [153 kB]
Get:61 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqwt-qt5-6 amd64 6.1.4-2 [418 kB]
Get:62 http://archive.ubuntu.com/ubuntu jammy/main amd64 python3-yaml amd64 5.4.1-1ubuntu1 [129 kB]
Get:63 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 udev amd64 249.11-0ubuntu3.16 [1,557 kB]
Get:64 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-core all 2.37-2build1 [1,041 kB]
Get:65 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-lyx all 2.3.6-1 [159 kB]
Get:66 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgck-1-0 amd64 3.40.0-4 [81.4 kB]
Get:67 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgcr-base-3-1 amd64 3.40.0-4 [209 kB]
Get:68 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgcr-ui-3-1 amd64 3.40.0-4 [135 kB]
Get:69 http://archive.ubuntu.com/ubuntu jammy/main amd64 gcr amd64 3.40.0-4 [60.3 kB]
Get:70 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libavahi-glib1 amd64 0.8-5ubuntu5.2 [8,296 B]
Get:71 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjson-glib-1.0-common all 1.6.6-1build1 [4,432 B]
Get:72 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjson-glib-1.0-0 amd64 1.6.6-1build1 [69.9 kB]
Get:73 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libmm-glib0 amd64 1.20.0-1~ubuntu22.04.4 [262 kB]
Get:74 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnotify4 amd64 0.7.9-3ubuntu5.22.04.1 [20.3 kB]
Get:75 http://archive.ubuntu.com/ubuntu jammy/main amd64 libproxy1v5 amd64 0.4.17-2 [51.9 kB]
Get:76 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking-common all 2.72.0-1 [3,718 B]
Get:77 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking-services amd64 2.72.0-1 [9,982 B]
Get:78 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:79 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:80 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking amd64 2.72.0-1 [69.8 kB]
Get:81 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsoup2.4-common all 2.74.2-3ubuntu0.5 [4,660 B]

In [ ]:
import subprocess
import os

input_file = "/content/ainsb.tif"
output_dir = "/content/jpgs_v1"

In [ ]:
subprocess.run([
    "gdal_translate",
    "-b", "1", "-b", "2", "-b", "3",    # Use the first 3 bands as RGB (adjust if needed)
    "-scale",                          # Auto-scale each band to 0-255
    "-ot", "Byte",                     # Convert to 8-bit
    input_file,
    "/content/ainsb_rgb.tif"
], check=True)

CompletedProcess(args=['gdal_translate', '-b', '1', '-b', '2', '-b', '3', '-scale', '-ot', 'Byte', '/content/ainsb.tif', '/content/ainsb_rgb.tif'], returncode=0)

In [ ]:




os.makedirs(output_dir, exist_ok=True)


cmd = [
    "gdal_retile.py",
    "-ps", "512", "512",
    "-targetDir", output_dir,
    "-of", "JPEG",
    "-co", "QUALITY=90",
    "/content/ainsb_rgb.tif"
]

subprocess.run(cmd, check=True)

CompletedProcess(args=['gdal_retile.py', '-ps', '512', '512', '-targetDir', '/content/jpgs_v1', '-of', 'JPEG', '-co', 'QUALITY=90', '/content/ainsb_rgb.tif'], returncode=0)

In [ ]:
from osgeo import gdal

ds = gdal.Open("/content/jpgs/input_rgb_1_1.jpg")
gt = ds.GetGeoTransform()

pixel_width = gt[1]
pixel_height = abs(gt[5])

print(f"Pixel size: {pixel_width} x {pixel_height}")

Pixel size: 0.30004465270125436 x 0.29996666666667293

/usr/local/lib/python3.11/dist-packages/osgeo/gdal.py:312: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(

In [ ]:
import requests
from PIL import Image
from io import BytesIO


zoom = 19
x_tile = 17500
y_tile = 10800

headers = {
    "Referer": "http://maps.google.cn/",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Accept-Encoding": "gzip, deflate",
    "Accept": "image/webp,image/apng,image/*,*/*;q=0.8",
    "Connection": "keep-alive"
}

tile_url = f"http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x_tile}&y={y_tile}&z={zoom}"


response = requests.get(tile_url, headers=headers)
response.text

'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/maps/vt?lyrs=s@189&amp;gl=cn&amp;x=17500&amp;y=10800&amp;z=19</code> was not found on this server.  <ins>That’s all we know.</ins>\n'

In [ ]:
import requests
from PIL import Image
from io import BytesIO

z, x, y = 19, 145000, 98000  # example tile coords — change to your area

url = f"https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"

resp = requests.get(url)
if resp.status_code == 200:
    img = Image.open(BytesIO(resp.content))
    img.save(f"sat_tile_{z}_{x}_{y}.jpg")
    print("Tile downloaded and saved.")
else:
    print("Failed to download tile:", resp.status_code)

Tile downloaded and saved.

In [ ]:
!pip install herepy

Collecting herepy
  Downloading herepy-3.6.5-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: Requests<3,>=2.25.1 in /usr/local/lib/python3.11/dist-packages (from herepy) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from Requests<3,>=2.25.1->herepy) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from Requests<3,>=2.25.1->herepy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from Requests<3,>=2.25.1->herepy) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from Requests<3,>=2.25.1->herepy) (2025.6.15)
Downloading herepy-3.6.5-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.8/53.8 kB 1.8 MB/s eta 0:00:00
Installing collected packages: herepy
Successfully installed herepy-3.6.5

In [ ]:
from herepy import (
    TrafficApi,
    IncidentsCriticalityStr,
    IncidentsCriticalityInt,
    FlowProximityAdditionalAttributes,
)

traffic_api = TrafficApi(api_key="LkXe9WOFiH3mNiSizdXgPupL0JLlIIeHDm9jHj0_wxc")

In [ ]:
traffic_api

In [ ]:
response = traffic_api.incidents_in_bounding_box(
    top_left=[52.5311, 13.3644],
    bottom_right=[52.5114, 13.4035],
    criticality=[
        IncidentsCriticalityStr.minor,
        IncidentsCriticalityStr.major,
        IncidentsCriticalityStr.critical,
    ],
)
print(response.as_dict())

HEREError: Error occurred on __get

In [ ]:
import requests

api_key = "LkXe9WOFiH3mNiSizdXgPupL0JLlIIeHDm9jHj0_wxc"

url = "https://data.traffic.hereapi.com/v7/flow"

params = {
    "in": "bbox:-7.8710453295757485,33.51104971198168,-7.3842807675301305,33.62978239688908",  # West, South, East, North
    "locationReferencing": "shape,olr",
    "minJamFactor": 0.0,
    "maxJamFactor": 10.0,
    "functionalClasses": "1,2,3,4,5",
    "apiKey": api_key
}

response = requests.get(url, params=params)
print(response.status_code)
print(response.json())

200
{'sourceUpdated': None, 'results': []}

In [ ]:





# fetches a traffic incident information within specified area
response = traffic_api.incidents_in_bounding_box(
    top_left=[52.5311, 13.3644],
    bottom_right=[52.5114, 13.4035],
    criticality=[
        IncidentsCriticalityStr.minor,
        IncidentsCriticalityStr.major,
        IncidentsCriticalityStr.critical,
    ],
)
print(response.as_dict())

# traffic incidents for a defined route
response = traffic_api.incidents_in_corridor(
    points=[[51.5072, -0.1275], [51.50781, -0.13112], [51.51006, -0.1346]],
    width=1000,
)
print(response.as_dict())

# traffic incident information within specified area
response = traffic_api.incidents_via_proximity(
    latitude=52.5311,
    longitude=13.3644,
    radius=15000,
    criticality=[
        IncidentsCriticalityInt.critical,
        IncidentsCriticalityInt.major,
    ],
)
print(response.as_dict())

# traffic flow information using a quadkey
response = traffic_api.flow_using_quadkey(quadkey="0313131311102300")
print(response.as_dict())

# traffic flow information within specified area
response = traffic_api.flow_within_boundingbox(
    top_left=[52.5311, 13.3644], bottom_right=[52.5114, 13.4035]
)
print(response.as_dict())

# traffic flow for a circle around a defined point
response = traffic_api.flow_using_proximity(
    latitude=51.5072, longitude=-0.1275, distance=100
)
print(response.as_dict())

# traffic flow information using proximity, returning shape and functional class
response = traffic_api.flow_using_proximity_returning_additional_attributes(
    latitude=51.5072,
    longitude=-0.1275,
    distance=100,
    attributes=[
        FlowProximityAdditionalAttributes.functional_class,
        FlowProximityAdditionalAttributes.shape,
    ],
)
print(response.as_dict())

# traffic flow information in specified area with a jam factor
response = traffic_api.flow_with_minimum_jam_factor(
    top_left=[52.5311, 13.3644],
    bottom_right=[52.5114, 13.4035],
    min_jam_factor=7,
)
print(response.as_dict())

# traffic flow for a defined route
response = traffic_api.flow_in_corridor(
    points=[[51.5072, -0.1275], [51.50781, -0.13112], [51.51006, -0.1346]],
    width=1000,
)
print(response.as_dict())

# flow availability requests allow you to see what traffic flow coverage exists in the current Traffic API
response = traffic_api.flow_availability_data()
print(response.as_dict())

# traffic flow including shape and functional class information
response = traffic_api.additional_attributes(
    quadkey="0313131311102312213",
    attributes=[FlowProximityAdditionalAttributes.functional_class],
)
print(response.as_dict())

In [ ]:
!wget https://data.humdata.org/dataset/32167ba5-ef67-4254-8eaf-04cdb8b90c1d/resource/79767bb0-ea9a-4bca-bfac-bfebc8d48a56/download/movement-distrubtion-may-2025.zip

--2025-06-30 09:18:24--  https://data.humdata.org/dataset/32167ba5-ef67-4254-8eaf-04cdb8b90c1d/resource/79767bb0-ea9a-4bca-bfac-bfebc8d48a56/download/movement-distrubtion-may-2025.zip
Resolving data.humdata.org (data.humdata.org)... 3.208.203.19, 3.225.87.125, 44.218.88.39
Connecting to data.humdata.org (data.humdata.org)|3.208.203.19|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s3.us-east-1.amazonaws.com/hdx-production-filestore/resources/79767bb0-ea9a-4bca-bfac-bfebc8d48a56/movement-distrubtion-may-2025.zip?AWSAccessKeyId=AKIAXYC32WNA75VNQHXP&Signature=PzTVAkxFdAjcZRgF12YGqVHZlpk%3D&Expires=1751275290 [following]
--2025-06-30 09:18:30--  https://s3.us-east-1.amazonaws.com/hdx-production-filestore/resources/79767bb0-ea9a-4bca-bfac-bfebc8d48a56/movement-distrubtion-may-2025.zip?AWSAccessKeyId=AKIAXYC32WNA75VNQHXP&Signature=PzTVAkxFdAjcZRgF12YGqVHZlpk%3D&Expires=1751275290
Resolving s3.us-east-1.amazonaws.com (s3.us-east-1.amazonaws.com)... 52.216.39.24, 52.217.90.94, 52.217.140.56, ...
Connecting to s3.us-east-1.amazonaws.com (s3.us-east-1.amazonaws.com)|52.216.39.24|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101475071 (97M) [application/zip]
Saving to: ‘movement-distrubtion-may-2025.zip’

movement-distrubtio 100%[===================>]  96.77M  80.0MB/s    in 1.2s

2025-06-30 09:18:31 (80.0 MB/s) - ‘movement-distrubtion-may-2025.zip’ saved [101475071/101475071]

In [ ]:
!unzip movement-distrubtion-may-2025.zip

Archive:  movement-distrubtion-may-2025.zip
  inflating: 1922039342088483_2025-05-18_2025-06-01_csv.zip
  inflating: __MACOSX/._1922039342088483_2025-05-18_2025-06-01_csv.zip
  inflating: 1922039342088483_2025-05-01_2025-05-18_csv.zip
  inflating: __MACOSX/._1922039342088483_2025-05-01_2025-05-18_csv.zip

In [ ]:
!unzip 1922039342088483_2025-05-18_2025-06-01_csv.zip

Archive:  1922039342088483_2025-05-18_2025-06-01_csv.zip
 extracting: 1922039342088483_2025-05-30.csv
 extracting: 1922039342088483_2025-05-18.csv
 extracting: 1922039342088483_2025-05-21.csv
 extracting: 1922039342088483_2025-05-26.csv
 extracting: 1922039342088483_2025-05-22.csv
 extracting: 1922039342088483_2025-05-28.csv
 extracting: 1922039342088483_2025-05-19.csv
 extracting: 1922039342088483_2025-05-20.csv
 extracting: 1922039342088483_2025-05-31.csv
 extracting: 1922039342088483_2025-06-01.csv
 extracting: 1922039342088483_2025-05-23.csv
 extracting: 1922039342088483_2025-05-25.csv
 extracting: 1922039342088483_2025-05-24.csv
 extracting: 1922039342088483_2025-05-27.csv
 extracting: 1922039342088483_2025-05-29.csv

Archive:  1922039342088483_2025-05-18.csv
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 1922039342088483_2025-05-18.csv or
        1922039342088483_2025-05-18.csv.zip, and cannot find 1922039342088483_2025-05-18.csv.ZIP, period.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("1922039342088483_2025-05-29.csv")
morocco_data = df[df["country"] == "MAR"]

array([2])

In [ ]:
morocco_data["home_to_ping_distance_category"].unique()

array(['[10, 100)', '100+', '0', '(0, 10)'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159388 entries, 0 to 159387
Data columns (total 7 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   gadm_id                          159388 non-null  object
 1   gadm_name                        159360 non-null  object
 2   country                          159388 non-null  object
 3   polygon_level                    159388 non-null  int64
 4   home_to_ping_distance_category   159388 non-null  object
 5   distance_category_ping_fraction  159388 non-null  float64
 6   ds                               159388 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 8.5+ MB

In [ ]:
morocco_data.reset_index(drop=True, inplace=True)

In [ ]:
morocco_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   gadm_id                          216 non-null    object
 1   gadm_name                        216 non-null    object
 2   country                          216 non-null    object
 3   polygon_level                    216 non-null    int64
 4   home_to_ping_distance_category   216 non-null    object
 5   distance_category_ping_fraction  216 non-null    float64
 6   ds                               216 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 11.9+ KB

In [ ]:
morocco_data.head()

,gadm_id,gadm_name,country,polygon_level,home_to_ping_distance_category,distance_category_ping_fraction,ds
0,MAR.7.1_1,Laâyoune,MAR,2,100+,0.087490,2025-05-30
1,MAR.7.1_1,Laâyoune,MAR,2,0,0.381978,2025-05-30
2,MAR.7.1_1,Laâyoune,MAR,2,"[10, 100)",0.031925,2025-05-30
3,MAR.7.1_1,Laâyoune,MAR,2,"(0, 10)",0.510324,2025-05-30
4,MAR.15.3_1,Taza,MAR,2,"(0, 10)",0.578693,2025-05-30

In [ ]:
morocco_data.to_csv("morocco_data_movement.csv", index=False)

In [ ]:
morocco_data["polygon_level"].unique()

array([2])

In [ ]:
!wget https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_MAR_shp.zip

--2025-06-30 09:32:55--  https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_MAR_shp.zip
Resolving biogeo.ucdavis.edu (biogeo.ucdavis.edu)... 128.120.228.172
Connecting to biogeo.ucdavis.edu (biogeo.ucdavis.edu)|128.120.228.172|:443... ^C

In [ ]:
!wget https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_MAR_gpkg.zip

--2025-06-30 09:33:20--  https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_MAR_gpkg.zip
Resolving biogeo.ucdavis.edu (biogeo.ucdavis.edu)... 128.120.228.172
Connecting to biogeo.ucdavis.edu (biogeo.ucdavis.edu)|128.120.228.172|:443... ^C

In [ ]:
!wget https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_MAR_2_sp.rds

--2025-06-30 09:33:55--  https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_MAR_2_sp.rds
Resolving biogeo.ucdavis.edu (biogeo.ucdavis.edu)... 128.120.228.172
Connecting to biogeo.ucdavis.edu (biogeo.ucdavis.edu)|128.120.228.172|:443... ^C

In [ ]:
!wget https://geodata.ucdavis.edu/gadm/gadm3.6/shp/gadm36_MAR_shp.zip

--2025-06-30 09:39:04--  https://geodata.ucdavis.edu/gadm/gadm3.6/shp/gadm36_MAR_shp.zip
Resolving geodata.ucdavis.edu (geodata.ucdavis.edu)... 128.120.146.30
Connecting to geodata.ucdavis.edu (geodata.ucdavis.edu)|128.120.146.30|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2494744 (2.4M) [application/zip]
Saving to: ‘gadm36_MAR_shp.zip’

gadm36_MAR_shp.zip  100%[===================>]   2.38M  4.23MB/s    in 0.6s

2025-06-30 09:39:05 (4.23 MB/s) - ‘gadm36_MAR_shp.zip’ saved [2494744/2494744]

In [ ]:
!unzip gadm36_MAR_shp.zip

Archive:  gadm36_MAR_shp.zip
 extracting: gadm36_MAR_0.cpg
  inflating: gadm36_MAR_0.dbf
  inflating: gadm36_MAR_0.prj
  inflating: gadm36_MAR_0.shp
  inflating: gadm36_MAR_0.shx
 extracting: gadm36_MAR_1.cpg
  inflating: gadm36_MAR_1.dbf
  inflating: gadm36_MAR_1.prj
  inflating: gadm36_MAR_1.shp
  inflating: gadm36_MAR_1.shx
 extracting: gadm36_MAR_2.cpg
  inflating: gadm36_MAR_2.dbf
  inflating: gadm36_MAR_2.prj
  inflating: gadm36_MAR_2.shp
  inflating: gadm36_MAR_2.shx
 extracting: gadm36_MAR_3.cpg
  inflating: gadm36_MAR_3.dbf
  inflating: gadm36_MAR_3.prj
  inflating: gadm36_MAR_3.shp
  inflating: gadm36_MAR_3.shx
 extracting: gadm36_MAR_4.cpg
  inflating: gadm36_MAR_4.dbf
  inflating: gadm36_MAR_4.prj
  inflating: gadm36_MAR_4.shp
  inflating: gadm36_MAR_4.shx
  inflating: license.txt

In [ ]:
maroc_traffic = pd.read_excel("/content/dimanche_traffic.xlsx")

In [ ]:
maroc_traffic.head()

,COMMUNE,ZIP code,index,Latitude,Longitude,index.1,Latitude.1,Longitude.1,KM,0,...,14.1,15.1,16.1,17.1,18.1,19.1,20.1,21.1,22.1,23.1
0,Echchallalate,28822,0,33.569686,-7.395306,1,33.647921,-7.408109,9954.0,10783.00,...,1.228987,1.254102,1.265823,1.332798,1.354564,1.362936,1.218940,1.195499,1.264148,1.222289
1,NaN,NaN,0,33.569686,-7.395306,2,33.615366,-7.458959,9098.0,12.85,...,1.456364,1.454532,1.439877,1.456364,1.450868,1.491170,1.450868,1.458196,1.458196,1.472851
2,NaN,NaN,0,33.569686,-7.395306,3,33.627898,-7.444039,8818.0,10783.00,...,1.313601,1.306041,1.277690,1.281470,1.309821,1.455356,1.315491,1.326831,1.326831,1.345732
3,NaN,NaN,0,33.569686,-7.395306,4,33.601050,-7.484443,11574.0,15417.00,...,1.487530,1.406889,1.494730,1.468809,1.604027,1.515528,1.535031,1.546570,1.553733,1.468809
4,NaN,NaN,1,33.647921,-7.408109,0,33.569686,-7.395306,9954.0,11.25,...,1.217266,1.235684,1.264148,1.223964,1.289264,1.257451,1.262474,1.237359,1.249079,1.212243

In [ ]:
maroc_traffic.fillna(method='ffill', inplace=True)

/tmp/ipython-input-67-530132147.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  maroc_traffic.fillna(method='ffill', inplace=True)

In [ ]:
maroc_traffic.head()

,COMMUNE,ZIP code,index,Latitude,Longitude,index.1,Latitude.1,Longitude.1,KM,0,...,14.1,15.1,16.1,17.1,18.1,19.1,20.1,21.1,22.1,23.1
0,Echchallalate,28822,0,33.569686,-7.395306,1,33.647921,-7.408109,9954.0,10783.00,...,1.228987,1.254102,1.265823,1.332798,1.354564,1.362936,1.218940,1.195499,1.264148,1.222289
1,Echchallalate,28822,0,33.569686,-7.395306,2,33.615366,-7.458959,9098.0,12.85,...,1.456364,1.454532,1.439877,1.456364,1.450868,1.491170,1.450868,1.458196,1.458196,1.472851
2,Echchallalate,28822,0,33.569686,-7.395306,3,33.627898,-7.444039,8818.0,10783.00,...,1.313601,1.306041,1.277690,1.281470,1.309821,1.455356,1.315491,1.326831,1.326831,1.345732
3,Echchallalate,28822,0,33.569686,-7.395306,4,33.601050,-7.484443,11574.0,15417.00,...,1.487530,1.406889,1.494730,1.468809,1.604027,1.515528,1.535031,1.546570,1.553733,1.468809
4,Echchallalate,28822,1,33.647921,-7.408109,0,33.569686,-7.395306,9954.0,11.25,...,1.217266,1.235684,1.264148,1.223964,1.289264,1.257451,1.262474,1.237359,1.249079,1.212243

In [ ]:
maroc_traffic.columns

Index([    'COMMUNE',    'ZIP code',       'index',    'Latitude',
         'Longitude',     'index.1',  'Latitude.1', 'Longitude.1',
                'KM',             0,             1,             2,
                   3,             4,             5,             6,
                   7,             8,             9,            10,
                  11,            12,            13,            14,
                  15,            16,            17,            18,
                  19,            20,            21,            22,
                  23,         '0.1',         '1.1',         '2.1',
               '3.1',         '4.1',         '5.1',         '6.1',
               '7.1',         '8.1',         '9.1',        '10.1',
              '11.1',        '12.1',        '13.1',        '14.1',
              '15.1',        '16.1',        '17.1',        '18.1',
              '19.1',        '20.1',        '21.1',        '22.1',
              '23.1'],
      dtype='object')

In [ ]:
columns_rename_minutes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
                          16, 17, 18, 19, 20, 21, 22, 23,
                          '0.1', '1.1', '2.1', '3.1', '4.1', '5.1', '6.1', '7.1', '8.1', '9.1',
                          '10.1', '11.1', '12.1', '13.1', '14.1', '15.1', '16.1', '17.1', '18.1',
                          '19.1', '20.1', '21.1', '22.1', '23.1']


rename_map = {}
for val in columns_rename_minutes:
    if isinstance(val, int):
        rename_map[val] = f"TravelTime_min_at_{val}h"
    else:
        hour = val.split('.')[0]
        rename_map[val] = f"TTI_at_{hour}h"


maroc_traffic.rename(columns=rename_map, inplace=True)

In [ ]:
maroc_traffic.head()

,COMMUNE,ZIP code,index,Latitude A,Longitude A,index.1,Latitude B,Longitude B,KM,TravelTime_min_at_0h,...,TTI_at_14h,TTI_at_15h,TTI_at_16h,TTI_at_17h,TTI_at_18h,TTI_at_19h,TTI_at_20h,TTI_at_21h,TTI_at_22h,TTI_at_23h
0,Echchallalate,28822,0,33.569686,-7.395306,1,33.647921,-7.408109,9954.0,10783.00,...,1.228987,1.254102,1.265823,1.332798,1.354564,1.362936,1.218940,1.195499,1.264148,1.222289
1,Echchallalate,28822,0,33.569686,-7.395306,2,33.615366,-7.458959,9098.0,12.85,...,1.456364,1.454532,1.439877,1.456364,1.450868,1.491170,1.450868,1.458196,1.458196,1.472851
2,Echchallalate,28822,0,33.569686,-7.395306,3,33.627898,-7.444039,8818.0,10783.00,...,1.313601,1.306041,1.277690,1.281470,1.309821,1.455356,1.315491,1.326831,1.326831,1.345732
3,Echchallalate,28822,0,33.569686,-7.395306,4,33.601050,-7.484443,11574.0,15417.00,...,1.487530,1.406889,1.494730,1.468809,1.604027,1.515528,1.535031,1.546570,1.553733,1.468809
4,Echchallalate,28822,1,33.647921,-7.408109,0,33.569686,-7.395306,9954.0,11.25,...,1.217266,1.235684,1.264148,1.223964,1.289264,1.257451,1.262474,1.237359,1.249079,1.212243

In [ ]:
lat_long_rename = {
    'Latitude': 'Latitude A',
    'Longitude': 'Longitude A',
    'Latitude.1': 'Latitude B',
    'Longitude.1': 'Longitude B'
}
maroc_traffic.rename(columns=lat_long_rename, inplace=True)

In [ ]:
maroc_traffic.drop(columns=["index", "index.1"], inplace=True)

In [ ]:
maroc_traffic['WKT'] = maroc_traffic.apply(
    lambda row: f"LINESTRING({row['Longitude A']} {row['Latitude A']}, {row['Longitude B']} {row['Latitude B']})",
    axis=1
)

In [ ]:
maroc_traffic.columns

Index(['COMMUNE', 'ZIP code', 'Latitude A', 'Longitude A', 'Latitude B',
       'Longitude B', 'KM', 'TravelTime_min_at_0h', 'TravelTime_min_at_1h',
       'TravelTime_min_at_2h', 'TravelTime_min_at_3h', 'TravelTime_min_at_4h',
       'TravelTime_min_at_5h', 'TravelTime_min_at_6h', 'TravelTime_min_at_7h',
       'TravelTime_min_at_8h', 'TravelTime_min_at_9h', 'TravelTime_min_at_10h',
       'TravelTime_min_at_11h', 'TravelTime_min_at_12h',
       'TravelTime_min_at_13h', 'TravelTime_min_at_14h',
       'TravelTime_min_at_15h', 'TravelTime_min_at_16h',
       'TravelTime_min_at_17h', 'TravelTime_min_at_18h',
       'TravelTime_min_at_19h', 'TravelTime_min_at_20h',
       'TravelTime_min_at_21h', 'TravelTime_min_at_22h',
       'TravelTime_min_at_23h', 'TTI_at_0h', 'TTI_at_1h', 'TTI_at_2h',
       'TTI_at_3h', 'TTI_at_4h', 'TTI_at_5h', 'TTI_at_6h', 'TTI_at_7h',
       'TTI_at_8h', 'TTI_at_9h', 'TTI_at_10h', 'TTI_at_11h', 'TTI_at_12h',
       'TTI_at_13h', 'TTI_at_14h', 'TTI_at_15h', 'TTI_at_16h', 'TTI_at_17h',
       'TTI_at_18h', 'TTI_at_19h', 'TTI_at_20h', 'TTI_at_21h', 'TTI_at_22h',
       'TTI_at_23h', 'WKT'],
      dtype='object')

In [ ]:
maroc_traffic.to_csv("traffic_dimanche.csv", index=False)

In [ ]:
bottom_left = (33.51104971198168, -7.8710453295757485)
top_right = (33.62978239688908, -7.3842807675301305)

# Calculate midpoint
mid_lat = (bottom_left[0] + top_right[0]) / 2
mid_lon = (bottom_left[1] + top_right[1]) / 2

point = f"{mid_lat},{mid_lon}"
print(point)

33.57041605443538,-7.6276630485529395

In [1]:
!pip install osmnx

Collecting osmnx
  Downloading osmnx-2.0.4-py3-none-any.whl.metadata (4.9 kB)
Collecting geopandas>=1.0 (from osmnx)
  Downloading geopandas-1.1.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.11/dist-packages (from osmnx) (3.5)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.11/dist-packages (from osmnx) (2.0.2)
Requirement already satisfied: pandas>=1.4 in /usr/local/lib/python3.11/dist-packages (from osmnx) (2.2.2)
Requirement already satisfied: requests>=2.27 in /usr/local/lib/python3.11/dist-packages (from osmnx) (2.32.3)
Collecting shapely>=2.0 (from osmnx)
  Downloading shapely-2.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting pyogrio>=0.7.2 (from geopandas>=1.0->osmnx)
  Downloading pyogrio-0.11.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from geopandas>=1.0->osmnx) (25.0)
Collecting pyproj>=3.5.0 (from geopandas>=1.0->osmnx)
  Downloading pyproj-3.7.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->osmnx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->osmnx) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->osmnx) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->osmnx) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->osmnx) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->osmnx) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->osmnx) (2025.6.15)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4->osmnx) (1.17.0)
Downloading osmnx-2.0.4-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.5/100.5 kB 2.1 MB/s eta 0:00:00
Downloading geopandas-1.1.1-py3-none-any.whl (338 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 338.4/338.4 kB 13.7 MB/s eta 0:00:00
Downloading shapely-2.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 67.4 MB/s eta 0:00:00
Downloading pyogrio-0.11.0-cp311-cp311-manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 59.2 MB/s eta 0:00:00
Downloading pyproj-3.7.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 117.5 MB/s eta 0:00:00
Installing collected packages: shapely, pyproj, pyogrio, geopandas, osmnx
Successfully installed geopandas-1.1.1 osmnx-2.0.4 pyogrio-0.11.0 pyproj-3.7.1 shapely-2.1.1

In [18]:
import osmnx as ox
import geopandas as gpd

 # west, south, east, north

north = 33.592101135
south = 33.547342932
east = -7.533424384
west = -7.635015048

G = ox.graph_from_bbox((west, south, east,north), network_type='drive')



# Get edges and nodes
nodes, edges = ox.graph_to_gdfs(G)

In [34]:
H = ox.graph_from_place("Ville Deroua, Casablanca, Morocco", network_type='drive')

# Get edges and nodes
nodes, edges = ox.graph_to_gdfs(H)

InsufficientResponseError: Nominatim geocoder returned 0 results for query 'Ville Deroua, Casablanca, Morocco'.

In [19]:
# Intersections: nodes with degree > 1 (connected to multiple roads)

intersection_nodes = [node for node, degree in G.degree() if degree > 1]

# Get coordinates of intersections
intersection_points = [(G.nodes[n]['y'], G.nodes[n]['x']) for n in intersection_nodes]

In [16]:
def get_graph_data(city = "Casablanca", country = "Morocco", coords = None, network_type = "drive" ):
  if coords:
    return ox.graph_from_bbox(coords, network_type=network_type)
  return ox.graph_from_place(f"{city}, {country}", network_type=network_type)

In [22]:
def jump_five_steps(inter_points, steps = 2):
  new_inter = []
  end = len(inter_points)
  for i in range(0, end, steps):
    new_inter.append(inter_points[i])
  return new_inter

In [17]:
def get_intersection_points(G, degree=2):

  intersection_nodes = [node for node, degree in G.degree() if degree >= 1]
  intersection_points = [(G.nodes[n]['y'], G.nodes[n]['x']) for n in intersection_nodes]
  return intersection_points

In [19]:
intersection_points[15], intersection_points[50]

((33.4996988, -7.6385716), (33.4900696, -7.6240527))

In [20]:
len(intersection_points)

12417

In [23]:
new_intersections = jump_five_steps(intersection_points)
len(new_intersections)

6209

In [30]:
import requests

def get_tomtom_data(latitude, longitude, zoom=19, api_key = "UkmMPDWyw5AEJ0rXg4IvlDZC2DrRNJIR"):
  url = f"https://api.tomtom.com/traffic/services/4/flowSegmentData/relative0/{zoom}/json?point={latitude}%2C{longitude}&unit=KMPH&openLr=true&key={api_key}"
  response = requests.get(url)
  if response.status_code != 200:
    print("Problem with fetching data...")
    return {}
  data = response.json()
  return data

In [ ]:
import requests

position = "33.59977%2C-7.523443"
url  = f"https://api.tomtom.com/traffic/services/4/flowSegmentData/relative0/21/json?point={position}&unit=KMPH&openLr=true&key=WowLoGT8X0hR2jpdhu65twZCOvty77P8"

response = requests.get(url)
print(response.status_code)

200

In [26]:
def coords_to_wkt_line(coords):
    if isinstance(coords, str):
        return coords
    points = ", ".join(f"{pt['longitude']} {pt['latitude']}" for pt in coords)
    return f"LINESTRING({points})"

In [27]:
def tomtom_to_seg(data):
    segments = data["flowSegmentData"]
    wkt_segment = coords_to_wkt_line(segments["coordinates"]["coordinate"])
    segments["coordinates"] = wkt_segment
    return segments

In [ ]:
l, k = (4, 5)
k

5

In [32]:
import datetime
def get_traffic_data(intersections, zoom = 19,  api_key ="UkmMPDWyw5AEJ0rXg4IvlDZC2DrRNJIR"):
  traffic_data = []

  for inter in intersections:
    latitude, longitude = inter
    data = get_tomtom_data(latitude, longitude, zoom, api_key)
    if not data:
      continue
    traffic_data.append(tomtom_to_seg(data))
  df = pd.DataFrame(traffic_data)
  df["created"] = datetime.datetime.now().isoformat()
  df.drop_duplicates(inplace=True)
  return df

In [14]:
datetime.datetime.now().isoformat()

'2025-07-03T08:58:50.517561'

In [33]:
import pandas as pd
road_traffic = get_traffic_data(new_intersections)
road_traffic.to_csv("road_try_03_07_25_10H.csv", index=False)
road_traffic.head()

,frc,currentSpeed,freeFlowSpeed,currentTravelTime,freeFlowTravelTime,confidence,roadClosure,coordinates,openlr,@version,created
0,FRC4,41,41,37,37,1.000000,False,LINESTRING(-7.567559077303741 33.5718061111469...,C/qeXhffkCaGBwGuAHQmGQ==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910
1,FRC2,27,35,1977,1525,0.985769,False,LINESTRING(-7.661367996516958 33.5821929715401...,C/qNShfhdBJIFwRc/M0STBoE9PylFEgPA5r/VhJLLQnu/0...,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910
2,FRC2,14,29,561,271,0.997796,False,LINESTRING(-7.615319832138567 33.5832095370735...,C/qVrBfhoxSQJQKL+TUiGg==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910
3,FRC4,21,25,213,179,0.985321,False,LINESTRING(-7.628785862500962 33.5933791418438...,C/qTORfjfSODFQRO/eojHQ==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910
4,FRC3,14,23,689,419,0.986865,False,LINESTRING(-7.609247310927429 33.5892150456770...,C/qWxxfiuxt3FfsnAegbmRf8Lv0gIwM=,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910

In [2]:
!pip install osmnx

Collecting osmnx
  Downloading osmnx-2.0.4-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: geopandas>=1.0 in /usr/local/lib/python3.11/dist-packages (from osmnx) (1.0.1)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.11/dist-packages (from osmnx) (3.5)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.11/dist-packages (from osmnx) (2.0.2)
Requirement already satisfied: pandas>=1.4 in /usr/local/lib/python3.11/dist-packages (from osmnx) (2.2.2)
Requirement already satisfied: requests>=2.27 in /usr/local/lib/python3.11/dist-packages (from osmnx) (2.32.3)
Requirement already satisfied: shapely>=2.0 in /usr/local/lib/python3.11/dist-packages (from osmnx) (2.1.1)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.11/dist-packages (from geopandas>=1.0->osmnx) (0.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from geopandas>=1.0->osmnx) (24.2)
Requirement already satisfied: pyproj>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from geopandas>=1.0->osmnx) (3.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->osmnx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->osmnx) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.4->osmnx) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->osmnx) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->osmnx) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->osmnx) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.27->osmnx) (2025.6.15)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4->osmnx) (1.17.0)
Downloading osmnx-2.0.4-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.5/100.5 kB 3.2 MB/s eta 0:00:00
Installing collected packages: osmnx
Successfully installed osmnx-2.0.4

In [38]:
import osmnx as ox

# # Define location and get graph
# G = ox.graph_from_place("Casablanca, Morocco", network_type="drive")

# # Convert graph to GeoDataFrame
# gdf = ox.graph_to_gdfs(G, nodes=False)
rows_lanes = {"lanes": [], "highway":[], "geometry":[], "oneway":[], "length":[]}
# # Check lane and width info
for i, row in edges.iterrows():
    rows_lanes["lanes"].append(row.get("lanes", None))
    rows_lanes["highway"].append(row.get("highway", None))
    rows_lanes["geometry"].append(row.get("geometry", None))
    rows_lanes["oneway"].append(row.get("oneway", None))
    rows_lanes["length"].append(row.get("length", None))

In [39]:
df = pd.DataFrame(rows_lanes)
df.head()

,lanes,highway,geometry,oneway,length
0,2,trunk_link,"LINESTRING (-7.5672869 33.5718889, -7.5667115 ...",True,419.844095
1,3,trunk,"LINESTRING (-7.5672869 33.5718889, -7.5660732 ...",True,251.339736
2,4,primary,"LINESTRING (-7.5944197 33.5604774, -7.594489 3...",True,231.944429
3,4,primary,"LINESTRING (-7.5950051 33.5625047, -7.5949717 ...",True,145.003989
4,3,primary,"LINESTRING (-7.5950051 33.5625047, -7.5949285 ...",True,20.133742

In [74]:
df["width_estimated"] = df.apply(estimer_largeur_route, axis=1)
df.head()

,lanes,highway,geometry,oneway,length,width_estimated
0,2,trunk_link,"LINESTRING (-7.5672869 33.5718889, -7.5667115 ...",True,419.844095,9.0
1,3,trunk,"LINESTRING (-7.5672869 33.5718889, -7.5660732 ...",True,251.339736,13.0
2,4,primary,"LINESTRING (-7.5944197 33.5604774, -7.594489 3...",True,231.944429,13.0
3,4,primary,"LINESTRING (-7.5950051 33.5625047, -7.5949717 ...",True,145.003989,13.0
4,3,primary,"LINESTRING (-7.5950051 33.5625047, -7.5949285 ...",True,20.133742,11.0

In [75]:
road_traffic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1319 entries, 0 to 6207
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   frc                 1319 non-null   object
 1   currentSpeed        1319 non-null   int64
 2   freeFlowSpeed       1319 non-null   int64
 3   currentTravelTime   1319 non-null   int64
 4   freeFlowTravelTime  1319 non-null   int64
 5   confidence          1319 non-null   float64
 6   roadClosure         1319 non-null   bool
 7   coordinates         1319 non-null   object
 8   openlr              1319 non-null   object
 9   @version            1319 non-null   object
 10  created             1319 non-null   object
dtypes: bool(1), float64(1), int64(4), object(5)
memory usage: 146.9+ KB

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33003 entries, 0 to 33002
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   lanes            28136 non-null  object
 1   highway          33003 non-null  object
 2   geometry         33003 non-null  object
 3   oneway           33003 non-null  bool
 4   length           33003 non-null  float64
 5   width_estimated  33003 non-null  float64
dtypes: bool(1), float64(2), object(3)
memory usage: 1.3+ MB

In [80]:
import geopandas as gpd
from shapely import wkt

# df["geometry"] = df["geometry"].apply(wkt.loads)
road_traffic["geometry"] = road_traffic["coordinates"].apply(wkt.loads)

In [81]:
gdf_osm = gpd.GeoDataFrame(df, geometry="geometry", crs="EPSG:4326")
gdf_tomtom = gpd.GeoDataFrame(road_traffic, geometry="geometry", crs="EPSG:4326")

In [86]:
tomtom_gdf = gdf_tomtom.to_crs("EPSG:3857")
osmnx_gdf = gdf_osm.to_crs("EPSG:3857")

In [95]:
tomtom_gdf = tomtom_gdf.reset_index().rename(columns={"index": "tomtom_id"})

In [96]:
from geopandas.tools import sjoin_nearest


tomtom_join_road = gpd.sjoin_nearest(tomtom_gdf, osmnx_gdf, how="left", distance_col="dist")

In [97]:
tomtom_join_road.head()

,tomtom_id,frc,currentSpeed,freeFlowSpeed,currentTravelTime,freeFlowTravelTime,confidence,roadClosure,coordinates,openlr,@version,created,geometry,index_right,lanes,highway,oneway,length,width_estimated,dist
0,0,FRC4,41,41,37,37,1.000000,False,LINESTRING(-7.567559077303741 33.5718061111469...,C/qeXhffkCaGBwGuAHQmGQ==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-842416.823 3971449.946, -842406.2...",0,2,trunk_link,True,419.844095,9.0,0.0
0,0,FRC4,41,41,37,37,1.000000,False,LINESTRING(-7.567559077303741 33.5718061111469...,C/qeXhffkCaGBwGuAHQmGQ==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-842416.823 3971449.946, -842406.2...",327,3,trunk,True,447.046820,13.0,0.0
1,1,FRC2,27,35,1977,1525,0.985769,False,LINESTRING(-7.661367996516958 33.5821929715401...,C/qNShfhdBJIFwRc/M0STBoE9PylFEgPA5r/VhJLLQnu/0...,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-852859.584 3972837.775, -852847.3...",8784,2,primary,True,90.532679,11.0,0.0
1,1,FRC2,27,35,1977,1525,0.985769,False,LINESTRING(-7.661367996516958 33.5821929715401...,C/qNShfhdBJIFwRc/M0STBoE9PylFEgPA5r/VhJLLQnu/0...,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-852859.584 3972837.775, -852847.3...",8956,1,tertiary,False,60.512813,6.5,0.0
1,1,FRC2,27,35,1977,1525,0.985769,False,LINESTRING(-7.661367996516958 33.5821929715401...,C/qNShfhdBJIFwRc/M0STBoE9PylFEgPA5r/VhJLLQnu/0...,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-852859.584 3972837.775, -852847.3...",16744,1,tertiary,False,60.512813,6.5,0.0

In [98]:
tomtom_best_match = (
    tomtom_join_road
    .sort_values("dist")
    .drop_duplicates(subset="tomtom_id")
    .reset_index(drop=True)
)

In [99]:
tomtom_best_match.head()

,tomtom_id,frc,currentSpeed,freeFlowSpeed,currentTravelTime,freeFlowTravelTime,confidence,roadClosure,coordinates,openlr,@version,created,geometry,index_right,lanes,highway,oneway,length,width_estimated,dist
0,4096,FRC5,17,30,169,95,0.980000,False,LINESTRING(-7.600998177100195 33.5616915168858...,C/qYSBfduSuuDQBn/UAqHQ==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-846139.247 3970098.657, -846125.8...",25452,2,residential,False,48.679555,6.50,0.0
1,4093,FRC3,20,32,190,119,1.000000,False,LINESTRING(-7.60429192977125 33.55360734277651...,C/qXrhfcQBt9Ev4gA1obDw==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-846505.905 3969018.741, -846512.4...",23537,3,secondary,True,9.714916,9.75,0.0
2,4099,FRC4,17,24,440,312,0.831099,False,LINESTRING(-7.591398551033677 33.5972509236803...,C/qaBxfkMiOMIwYk+1gjHw==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-845070.621 3974850.022, -845064.9...",9619,2,tertiary,False,89.923090,6.50,0.0
3,4071,FRC4,17,21,149,121,0.976053,False,"LINESTRING(-7.62868796187189 33.5934636240163,...",C/qTPRfjgSOTDP4V/h4jBA==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-849221.659 3974343.879, -849232.5...",8680,4,primary,True,93.710354,13.00,0.0
4,4028,FRC3,26,34,380,290,0.957909,False,LINESTRING(-7.552141739882558 33.5514696298508...,C/qhLBfb3BpzLvb9+g0aBw==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-840700.573 3968733.194, -840741.0...",32570,2,residential,False,51.456709,6.50,0.0

In [100]:
tomtom_best_match.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tomtom_id           1319 non-null   int64
 1   frc                 1319 non-null   object
 2   currentSpeed        1319 non-null   int64
 3   freeFlowSpeed       1319 non-null   int64
 4   currentTravelTime   1319 non-null   int64
 5   freeFlowTravelTime  1319 non-null   int64
 6   confidence          1319 non-null   float64
 7   roadClosure         1319 non-null   bool
 8   coordinates         1319 non-null   object
 9   openlr              1319 non-null   object
 10  @version            1319 non-null   object
 11  created             1319 non-null   object
 12  geometry            1319 non-null   geometry
 13  index_right         1319 non-null   int64
 14  lanes               1218 non-null   object
 15  highway             1319 non-null   object
 16  oneway              1319 non-null   bool
 17  length              1319 non-null   float64
 18  width_estimated     1319 non-null   float64
 19  dist                1319 non-null   float64
dtypes: bool(2), float64(4), geometry(1), int64(6), object(7)
memory usage: 188.2+ KB

In [101]:
tomtom_best_match.to_csv("tomtom_best_match_road.csv", index=False)

In [114]:
tomtom_best_match = pd.read_csv("tomtom_best_match_road.csv")

In [119]:
def clean_lanes(val):
    if isinstance(val, list):
        return val[0]
    return val

tomtom_best_match["lanes_clean"] = tomtom_best_match["lanes"].apply(clean_lanes)


tomtom_best_match["lanes_clean"] = pd.to_numeric(tomtom_best_match["lanes_clean"], errors="coerce")

In [128]:
tomtom_best_match["lanes_clean"].unique()

array([ 2.,  3.,  4., nan,  1.,  5.,  6.])

In [120]:
lanes_by_highway = (
    tomtom_best_match.dropna(subset=["lanes_clean"])
      .groupby("highway")["lanes_clean"]
      .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else x.median())
      .to_dict()
)

In [122]:
lanes_by_highway

{'crossing': 2.0,
 'living_street': 1.0,
 'primary': 3.0,
 'primary_link': 1.0,
 'residential': 2.0,
 'secondary': 3.0,
 'secondary_link': 1.0,
 'tertiary': 2.0,
 'tertiary_link': 1.0,
 'trunk': 3.0,
 'trunk_link': 1.0,
 'unclassified': 2.0}

In [124]:
tomtom_best_match["lanes_filled"] = tomtom_best_match.apply(
    lambda row: lanes_by_highway.get(row["highway"]) if pd.isna(row["lanes_clean"]) else row["lanes_clean"],
    axis=1
)

In [125]:
tomtom_best_match["lanes_filled"] = tomtom_best_match["lanes_filled"].astype("Int64")

In [129]:
tomtom_best_match["lanes_filled"].isna().sum()

np.int64(0)

In [130]:
tomtom_best_match.drop(columns=["lanes", "lanes_clean"], inplace=True)

In [131]:
tomtom_best_match.rename(columns={"lanes_filled": "lanes"}, inplace=True)

In [132]:
tomtom_best_match.to_csv("traffic_flow_casa_03_07_25_17H.csv", index=False)

In [116]:
tomtom_best_match["lanes"].unique()

array(['2', '3', '4', nan, '1', '5', "['2', '4']", '6', "['4', '3']",
       "['5', '3']", "['1', '3']", "['3', '1']"], dtype=object)

In [110]:
lanes_by_highway = (
    df.dropna(subset=["lanes"])
      .groupby("highway")["lanes"]
      .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else x.median())
      .to_dict()
)

TypeError: unhashable type: 'list'

In [88]:
tomtom_join_road.head()

,frc,currentSpeed,freeFlowSpeed,currentTravelTime,freeFlowTravelTime,confidence,roadClosure,coordinates,openlr,@version,created,geometry,index_right,lanes,highway,oneway,length,width_estimated,dist
0,FRC4,41,41,37,37,1.000000,False,LINESTRING(-7.567559077303741 33.5718061111469...,C/qeXhffkCaGBwGuAHQmGQ==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-842416.823 3971449.946, -842406.2...",0,2,trunk_link,True,419.844095,9.0,0.0
0,FRC4,41,41,37,37,1.000000,False,LINESTRING(-7.567559077303741 33.5718061111469...,C/qeXhffkCaGBwGuAHQmGQ==,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-842416.823 3971449.946, -842406.2...",327,3,trunk,True,447.046820,13.0,0.0
1,FRC2,27,35,1977,1525,0.985769,False,LINESTRING(-7.661367996516958 33.5821929715401...,C/qNShfhdBJIFwRc/M0STBoE9PylFEgPA5r/VhJLLQnu/0...,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-852859.584 3972837.775, -852847.3...",8784,2,primary,True,90.532679,11.0,0.0
1,FRC2,27,35,1977,1525,0.985769,False,LINESTRING(-7.661367996516958 33.5821929715401...,C/qNShfhdBJIFwRc/M0STBoE9PylFEgPA5r/VhJLLQnu/0...,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-852859.584 3972837.775, -852847.3...",8956,1,tertiary,False,60.512813,6.5,0.0
1,FRC2,27,35,1977,1525,0.985769,False,LINESTRING(-7.661367996516958 33.5821929715401...,C/qNShfhdBJIFwRc/M0STBoE9PylFEgPA5r/VhJLLQnu/0...,traffic-service-flow 1.0.146,2025-07-03T13:52:44.585910,"LINESTRING (-852859.584 3972837.775, -852847.3...",16744,1,tertiary,False,60.512813,6.5,0.0

In [89]:
tomtom_join_road.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 44127 entries, 0 to 6207
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   frc                 44127 non-null  object
 1   currentSpeed        44127 non-null  int64
 2   freeFlowSpeed       44127 non-null  int64
 3   currentTravelTime   44127 non-null  int64
 4   freeFlowTravelTime  44127 non-null  int64
 5   confidence          44127 non-null  float64
 6   roadClosure         44127 non-null  bool
 7   coordinates         44127 non-null  object
 8   openlr              44127 non-null  object
 9   @version            44127 non-null  object
 10  created             44127 non-null  object
 11  geometry            44127 non-null  geometry
 12  index_right         44127 non-null  int64
 13  lanes               41125 non-null  object
 14  highway             44127 non-null  object
 15  oneway              44127 non-null  bool
 16  length              44127 non-null  float64
 17  width_estimated     44127 non-null  float64
 18  dist                44127 non-null  float64
dtypes: bool(2), float64(4), geometry(1), int64(5), object(7)
memory usage: 7.2+ MB

In [73]:
import math
def estimer_largeur_route(row):


    defaults = {
        'motorway': 18,
        'motorway_link': 9,
        'trunk': 13,
        'trunk_link': 9,
        'primary': 11,
        'primary_link': 9,
        'secondary': 8.5,
        'secondary_link': 7.5,
        'tertiary': 6.5,
        'tertiary_link': 6,
        'residential': 6,
        'unclassified': 5
    }

    highway = row.get('highway', None)

    if isinstance(highway, list):
        highway = highway[0] if highway else None


    default_width = defaults.get(highway, 6)
    lanes = row.get('lanes', None)
    voie_moyenne = 3.25


    if lanes is None or (isinstance(lanes, float) and math.isnan(lanes)):
        return default_width

    try:

        if isinstance(lanes, list):
            lanes_int = max(int(float(l)) for l in lanes)


        elif isinstance(lanes, str):
            lanes_int = int(float(lanes))

        elif isinstance(lanes, (int, float)):
            lanes_int = int(lanes)

        else:
            return default_width

        est_width = lanes_int * voie_moyenne
        return max(est_width, default_width)

    except Exception as e:
        print(f"Error with lanes={lanes}: {e}")
        return default_width

In [9]:
def get_roads_data(G):
  gdf = ox.graph_to_gdfs(G, nodes=False)
  rows_lanes = {"lanes": [], "highway":[], "geometry":[], "oneway":[], "length":[]}
  for i, row in gdf.iterrows():
      rows_lanes["lanes"].append(row.get("lanes", None))
      rows_lanes["highway"].append(row.get("highway", None))
      rows_lanes["geometry"].append(row.get("geometry", None))
      rows_lanes["oneway"].append(row.get("oneway", None))
      rows_lanes["length"].append(row.get("length", None))
  df = pd.DataFrame(rows_lanes)
  df["width_estimated"] = df.apply(estimer_largeur_route, axis=1)
  return df

In [40]:
tf = get_roads_data(G)

TypeError: Each query must be a dict or a string.

In [ ]:
import geopandas as gpd
from shapely.geometry import LineString
from shapely.ops import nearest_points

# Make sure same CRS!
tomtom_gdf = tomtom_gdf.to_crs("EPSG:4326")
osmnx_gdf = osmnx_gdf.to_crs("EPSG:4326")

In [62]:
row.keys()

Index(['osmid', 'highway', 'lanes', 'maxspeed', 'oneway', 'reversed', 'length',
       'geometry', 'name', 'ref', 'access', 'junction', 'bridge', 'tunnel',
       'service', 'width'],
      dtype='object')

In [75]:
type(row["geometry"])

shapely.geometry.linestring.LineString

In [77]:
landf = pd.DataFrame(rows_lanes)
landf.head()

,lanes,highway,geometry,oneway,length
0,1,motorway_link,"LINESTRING (-7.6283012 33.5007107, -7.6282869 ...",True,302.753489
1,2,motorway,"LINESTRING (-7.6283012 33.5007107, -7.6283658 ...",True,253.358618
2,2,trunk_link,"LINESTRING (-7.5672869 33.5718889, -7.5667115 ...",True,419.844095
3,3,trunk,"LINESTRING (-7.5672869 33.5718889, -7.5660732 ...",True,251.339736
4,1,trunk_link,"LINESTRING (-7.6319347 33.5170524, -7.6319542 ...",True,257.276759

In [79]:
landf.to_csv("road_test_info.csv", index=False)

In [78]:
landf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98092 entries, 0 to 98091
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   lanes     74976 non-null  object
 1   highway   98092 non-null  object
 2   geometry  98092 non-null  object
 3   oneway    98092 non-null  bool
 4   length    98092 non-null  float64
dtypes: bool(1), float64(1), object(3)
memory usage: 3.1+ MB

In [61]:
landf["highway"].value_counts()

highway
residential                          80574
tertiary                              7112
secondary                             3051
primary                               2614
living_street                         2030
unclassified                          1239
trunk                                  496
primary_link                           231
trunk_link                             215
secondary_link                         179
tertiary_link                          158
busway                                  99
[living_street, residential]            56
motorway_link                           16
motorway                                12
[trunk, motorway]                        2
[residential, unclassified]              2
crossing                                 2
[residential, tertiary]                  1
[trunk_link, trunk, primary]             1
[secondary, trunk_link]                  1
[primary_link, primary, tertiary]        1
Name: count, dtype: int64

In [ ]:
def estimer_largeur(row):
    highway = row['highway']
    lanes = row.get('lanes', None)
    base_width = {
        'motorway': 18,
        'motorway_link': 9,
        'trunk': 13,
        'trunk_link': 9,
        'primary': 12,
        'primary_link': 9,
        'secondary': 9,
        'secondary_link': 7,
        'tertiary': 7,
        'tertiary_link': 6,
        'residential': 6,
        'living_street': 5,
        'unclassified': 5,
        'busway': 4,
        '[living_street, residential]': 5,
        '[trunk, motorway]': 17,
        '[residential, unclassified]': 5,
    }

    if lanes:
        return lanes * 3.25
    else:
        return base_width.get(highway, 6)

In [58]:
lanes

['1', '2']

In [ ]:
!pip install googlemaps

Collecting googlemaps
  Downloading googlemaps-4.10.0.tar.gz (33 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.11/dist-packages (from googlemaps) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2025.6.15)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.10.0-py3-none-any.whl size=40714 sha256=3e6d93316f0e296589fa132b70c029bf9d6c392be3ed3afe0159a9643aadb034
  Stored in directory: /root/.cache/pip/wheels/f1/09/77/3cc2f5659cbc62341b30f806aca2b25e6a26c351daa5b1f49a
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.10.0

In [ ]:
import googlemaps

gmaps = googlemaps.Client("AIzaSyCRX7uW8k7Hrfk77QyCIUZlXynSoSFYoSE")

In [ ]:
!pip install polyline

Collecting polyline
  Downloading polyline-2.0.2-py3-none-any.whl.metadata (6.4 kB)
Downloading polyline-2.0.2-py3-none-any.whl (6.0 kB)
Installing collected packages: polyline
Successfully installed polyline-2.0.2

In [ ]:
!wget https://maps.googleapis.com/maps/api/distancematrix/json?destinations=New%20York%20City%2C%20NY&origins=Washington%2C%20DC%7CBoston&units=imperial&key=AIzaSyCRX7uW8k7Hrfk77QyCIUZlXynSoSFYoSE

--2025-06-30 16:13:48--  https://maps.googleapis.com/maps/api/distancematrix/json?destinations=New%20York%20City%2C%20NY
Resolving maps.googleapis.com (maps.googleapis.com)... 173.194.215.95, 74.125.26.95, 173.194.217.95, ...
Connecting to maps.googleapis.com (maps.googleapis.com)|173.194.215.95|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 294 [application/json]
Saving to: ‘json?destinations=New York City, NY’

json?destinations=N 100%[===================>]     294  --.-KB/s    in 0s

2025-06-30 16:13:48 (68.5 MB/s) - ‘json?destinations=New York City, NY’ saved [294/294]